### ISSUE TITLE
Can I still contribute to this project 

### ISSUE THREAD

**Issue by K-RD** [SoftTech-Global/singlepage#54]
I would like to update the styling in the following files 
[alisherhtml.html](https://github.com/SoftTech-Global/singlepage/blob/master/alisherhtml.html)- full page styling
[suppergirl.html](https://github.com/SoftTech-Global/singlepage/blob/master/suppergirl.html)- button styling
[Scorpio-BS.html](https://github.com/SoftTech-Global/singlepage/blob/master/Scorpio-BS.html)-DropDown Menu Styling

 I would also like to add my own pages in the projects. Can I do that, please let me know.

**Comment by mrsaifullah52** [comment]
Yes you can.
